version: '3.8'

networks:
  flask_search:
    driver: bridge

volumes:
  search_data: {}

services:
  search:
    image: getmeili/meilisearch
    container_name: search
    restart: always
    ports:
      - 7700:7700
    volumes:
      - search_data:/data.ms
    networks:
      - flask_search
    env_file:
      - search.env